FROM gcr.io/code-intelligence/securityrat_build

RUN mkdir -p /home/perl/.npm 
RUN mkdir -p /home/perl/.cache
RUN chown -R 1000:1000 "/home/perl"

RUN mkdir -p /home/roman/.npm 
RUN mkdir -p /home/roman/.cache
RUN chown -R 1000:1000 "/home/roman"

RUN mkdir -p /home/serj/.npm 
RUN mkdir -p /home/serj/.cache
RUN chown -R 1000:1000 "/home/serj"

# RUN mkdir -p /root/.npm 
# RUN mkdir -p /root/.cache
# RUN chown -R 1000:1000 "/root"